vim.g.mapleader = " "

--keymap cheat sheet
vim.keymap.set("n", "<leader>0", function()
    while(vim.fn.winnr() ~= 1) do
        vim.cmd('wincmd h')
    end
    if(vim.fn.bufname() == '/home/mads/myNvimCheatSheat.txt')then
        vim.cmd('close')
        return
    end
    vim.cmd('50 vsplit')
    vim.cmd('e ~/myNvimCheatSheat.txt')
end)
vim.keymap.set("n", "<leader>E", vim.cmd.Ex)
vim.keymap.set("n", "<leader>L", function()
    vim.cmd('tabnew')
    vim.cmd('e ~/.config/nvim')
end)
vim.keymap.set("n", "<leader><leader>", vim.cmd.w)
vim.keymap.set("n", "<cr>", [[i<cr><esc>]])
vim.keymap.set("n", "<leader>_", function() vim.cmd('!fixCap')end)
vim.keymap.set("n", "<leader>W", function() vim.cmd('SudaWrite')end)
vim.keymap.set("n", "<leader>Y", [["+Y]])
vim.keymap.set("n", "<leader>b", "<c-^>")
vim.keymap.set("n", "<leader>d", "yyp")
vim.keymap.set("n", "<leader>e", function() vim.cmd('e .') end)
vim.keymap.set("n", "<leader>u", "U")
vim.keymap.set("n", "<leader>q", vim.cmd.q)
vim.keymap.set("n", "<leader>o", "o<esc>")
vim.keymap.set("n", "<leader>s", [[:%s/\<<C-r><C-w>\>/<C-r><C-w>/gI<Left><Left><Left>]])
vim.keymap.set("n", "<leader>;", function() vim.cmd('PrettierAsync') end)
vim.keymap.set({ "n", "v" }, "<leader>y", [["+y]])
vim.keymap.set({ "n", "v" }, "<leader>p", [["+p]])
vim.keymap.set({ "n", "v" }, "<leader>P", [["+P]])
--vim.keymap.set({"n"}, "d" ,[["_d]])
vim.keymap.set({"n"}, "yd" ,[[dd]])
vim.keymap.set("n", "<C-d>", "<C-d>")
vim.keymap.set("v", "<leader>/", "I{/*<esc>A*/}<esc>")
vim.keymap.set("i", "<C-d>", "<cr><c-o>k<c-o>$")
vim.keymap.set("i", "<A-l>", "<C-o>l")
vim.keymap.set("i", "<A-j>", "<C-o>j")
vim.keymap.set("i", "<A-k>", "<C-o>k")
vim.keymap.set("i", "<A-h>", "<C-o>h")
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("n", "n", "nzzzv")
vim.keymap.set("n", "N", "Nzzzv")
vim.keymap.set("n", "-", "$")
vim.keymap.set("n", "Q", "<nop>")
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv")
vim.keymap.set("n", "J", "mzJ`z")
vim.keymap.set("n", "U", "<c-r>")
