local builtin = require('telescope.builtin')
local utils = require('telescope.utils')
vim.keymap.set('n', '<leader>f', builtin.find_files, {})
vim.keymap.set('n', '<leader>F', builtin.git_files, {})
vim.keymap.set('n', '<leader>g', function()
	builtin.grep_string({search = vim.fn.input("Grep > ")})
end)
vim.keymap.set('n', '<leader>/', function()
	builtin.grep_string({cwd = utils.buffer_dir(), search = vim.fn.input("Grep > ")})
end)
